// <auto-generated>
// Code generated by protoc-gen-csharp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-csharp-tableau-loader v0.1.0
// - protoc                           v3.19.3
// source: hero_conf.proto
// </auto-generated>
#nullable enable
using pb = global::Google.Protobuf;
namespace Tableau
{
    public class HeroConf : Messager, IMessagerName
    {
        // OrderedMap types.
        public class OrderedMap_Hero_AttrMap : SortedDictionary<string, Protoconf.HeroConf.Types.Hero.Types.Attr>;

        public class OrderedMap_HeroValue(OrderedMap_Hero_AttrMap item1, Protoconf.HeroConf.Types.Hero item2)
            : Tuple<OrderedMap_Hero_AttrMap, Protoconf.HeroConf.Types.Hero>(item1, item2);
        public class OrderedMap_HeroMap : SortedDictionary<string, OrderedMap_HeroValue>;

        private OrderedMap_HeroMap _orderedMap = [];

        private Protoconf.HeroConf _data = new();

        public static string Name() => Protoconf.HeroConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.HeroConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.HeroConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.HeroConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        protected override bool ProcessAfterLoad()
        {
            // OrderedMap init.
            _orderedMap.Clear();
            foreach (var (key1, value1) in _data.HeroMap)
            {
                var ordered_map1 = new OrderedMap_Hero_AttrMap();
                foreach (var (key2, value2) in value1.AttrMap)
                {
                    ordered_map1[key2] = value2;
                }
                _orderedMap[key1] = new OrderedMap_HeroValue(ordered_map1, value1);
            }
            return true;
        }

        public Protoconf.HeroConf.Types.Hero? Get1(string name) =>
            _data.HeroMap?.TryGetValue(name, out var val) == true ? val : null;

        public Protoconf.HeroConf.Types.Hero.Types.Attr? Get2(string name, string title) =>
            Get1(name)?.AttrMap?.TryGetValue(title, out var val) == true ? val : null;

        // OrderedMap accessers.
        public ref readonly OrderedMap_HeroMap GetOrderedMap() => ref _orderedMap;

        public OrderedMap_Hero_AttrMap? GetOrderedMap1(string name) =>
            _orderedMap.TryGetValue(name, out var value) ? value.Item1 : null;
    }

    public class HeroBaseConf : Messager, IMessagerName
    {
        private Protoconf.HeroBaseConf _data = new();

        public static string Name() => Protoconf.HeroBaseConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.HeroBaseConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.HeroBaseConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.HeroBaseConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        public Base.Hero? Get1(string name) =>
            _data.HeroMap?.TryGetValue(name, out var val) == true ? val : null;

        public Base.Item? Get2(string name, string id) =>
            Get1(name)?.ItemMap?.TryGetValue(id, out var val) == true ? val : null;
    }
}
