// <auto-generated>
// Code generated by protoc-gen-csharp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-csharp-tableau-loader v0.1.0
// - protoc                           (unknown)
// source: hero_conf.proto
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using pb = global::Google.Protobuf;
namespace Tableau
{
    /// <summary>
    /// HeroConf is a wrapper around protobuf message Protoconf.HeroConf.
    /// </summary>
    public class HeroConf : Messager, IMessagerName
    {
        // OrderedMap types.
        public class OrderedMap_Hero_AttrMap : SortedDictionary<string, Protoconf.HeroConf.Types.Hero.Types.Attr> { }

        public class OrderedMap_HeroValue : Tuple<OrderedMap_Hero_AttrMap, Protoconf.HeroConf.Types.Hero>
        {
            public OrderedMap_HeroValue(OrderedMap_Hero_AttrMap item1, Protoconf.HeroConf.Types.Hero item2) : base(item1, item2) { }
        }
        public class OrderedMap_HeroMap : SortedDictionary<string, OrderedMap_HeroValue> { }

        private OrderedMap_HeroMap _orderedMap = new OrderedMap_HeroMap();

        private Protoconf.HeroConf _data = new();

        /// <summary>
        /// Name returns the HeroConf's message name.
        /// </summary>
        public string Name() => Protoconf.HeroConf.Descriptor.Name;

        /// <summary>
        /// Load loads HeroConf's content in the given dir, based on format and messager options.
        /// </summary>
        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.HeroConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.HeroConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(Util.GetErrMsg()))
                {
                    Util.SetErrMsg($"failed to load HeroConf: {ex.Message}");
                }
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        /// <summary>
        /// Data returns the HeroConf's inner message data.
        /// </summary>
        public ref readonly Protoconf.HeroConf Data() => ref _data;

        /// <summary>
        /// Message returns the HeroConf's inner message data.
        /// </summary>
        public override pb::IMessage? Message() => _data;

        /// <summary>
        /// ProcessAfterLoad runs after this messager is loaded.
        /// </summary>
        protected override bool ProcessAfterLoad()
        {
            // OrderedMap init.
            _orderedMap.Clear();
            foreach (var (key1, value1) in _data.HeroMap)
            {
                var ordered_map1 = new OrderedMap_Hero_AttrMap();
                foreach (var (key2, value2) in value1.AttrMap)
                {
                    ordered_map1[key2] = value2;
                }
                _orderedMap[key1] = new OrderedMap_HeroValue(ordered_map1, value1);
            }
            return true;
        }

        /// <summary>
        /// Get1 finds value in the 1st-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.HeroConf.Types.Hero? Get1(string name) =>
            _data.HeroMap?.TryGetValue(name, out var val) == true ? val : null;

        /// <summary>
        /// Get2 finds value in the 2nd-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.HeroConf.Types.Hero.Types.Attr? Get2(string name, string title) =>
            Get1(name)?.AttrMap?.TryGetValue(title, out var val) == true ? val : null;

        // OrderedMap accessers.
        /// <summary>
        /// GetOrderedMap returns the 1st-level ordered map.
        /// </summary>
        public ref readonly OrderedMap_HeroMap GetOrderedMap() => ref _orderedMap;

        /// <summary>
        /// GetOrderedMap1 finds value in the 1st-level ordered map.
        /// It will return null if the key is not found.
        /// </summary>
        public OrderedMap_Hero_AttrMap? GetOrderedMap1(string name) =>
            _orderedMap.TryGetValue(name, out var value) ? value.Item1 : null;
    }

    /// <summary>
    /// HeroBaseConf is a wrapper around protobuf message Protoconf.HeroBaseConf.
    /// </summary>
    public class HeroBaseConf : Messager, IMessagerName
    {
        private Protoconf.HeroBaseConf _data = new();

        /// <summary>
        /// Name returns the HeroBaseConf's message name.
        /// </summary>
        public string Name() => Protoconf.HeroBaseConf.Descriptor.Name;

        /// <summary>
        /// Load loads HeroBaseConf's content in the given dir, based on format and messager options.
        /// </summary>
        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.HeroBaseConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.HeroBaseConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(Util.GetErrMsg()))
                {
                    Util.SetErrMsg($"failed to load HeroBaseConf: {ex.Message}");
                }
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        /// <summary>
        /// Data returns the HeroBaseConf's inner message data.
        /// </summary>
        public ref readonly Protoconf.HeroBaseConf Data() => ref _data;

        /// <summary>
        /// Message returns the HeroBaseConf's inner message data.
        /// </summary>
        public override pb::IMessage? Message() => _data;

        /// <summary>
        /// Get1 finds value in the 1st-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Base.Hero? Get1(string name) =>
            _data.HeroMap?.TryGetValue(name, out var val) == true ? val : null;

        /// <summary>
        /// Get2 finds value in the 2nd-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Base.Item? Get2(string name, string id) =>
            Get1(name)?.ItemMap?.TryGetValue(id, out var val) == true ? val : null;
    }
}
