// <auto-generated>
// Code generated by protoc-gen-csharp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-csharp-tableau-loader v0.1.0
// - protoc                           (unknown)
// source: patch_conf.proto
// </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using pb = global::Google.Protobuf;
namespace Tableau
{
    /// <summary>
    /// PatchReplaceConf is a wrapper around protobuf message Protoconf.PatchReplaceConf.
    /// </summary>
    public class PatchReplaceConf : Messager, IMessagerName
    {
        private Protoconf.PatchReplaceConf _data = new();

        /// <summary>
        /// Name returns the PatchReplaceConf's message name.
        /// </summary>
        public string Name() => Protoconf.PatchReplaceConf.Descriptor.Name;

        /// <summary>
        /// Load loads PatchReplaceConf's content in the given dir, based on format and messager options.
        /// </summary>
        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.PatchReplaceConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.PatchReplaceConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(Util.GetErrMsg()))
                {
                    Util.SetErrMsg($"failed to load PatchReplaceConf: {ex.Message}");
                }
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        /// <summary>
        /// Data returns the PatchReplaceConf's inner message data.
        /// </summary>
        public ref readonly Protoconf.PatchReplaceConf Data() => ref _data;

        /// <summary>
        /// Message returns the PatchReplaceConf's inner message data.
        /// </summary>
        public override pb::IMessage? Message() => _data;
    }

    /// <summary>
    /// PatchMergeConf is a wrapper around protobuf message Protoconf.PatchMergeConf.
    /// </summary>
    public class PatchMergeConf : Messager, IMessagerName
    {
        private Protoconf.PatchMergeConf _data = new();

        /// <summary>
        /// Name returns the PatchMergeConf's message name.
        /// </summary>
        public string Name() => Protoconf.PatchMergeConf.Descriptor.Name;

        /// <summary>
        /// Load loads PatchMergeConf's content in the given dir, based on format and messager options.
        /// </summary>
        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.PatchMergeConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.PatchMergeConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(Util.GetErrMsg()))
                {
                    Util.SetErrMsg($"failed to load PatchMergeConf: {ex.Message}");
                }
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        /// <summary>
        /// Data returns the PatchMergeConf's inner message data.
        /// </summary>
        public ref readonly Protoconf.PatchMergeConf Data() => ref _data;

        /// <summary>
        /// Message returns the PatchMergeConf's inner message data.
        /// </summary>
        public override pb::IMessage? Message() => _data;

        /// <summary>
        /// Get1 finds value in the 1st-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.Item? Get1(uint id) =>
            _data.ItemMap?.TryGetValue(id, out var val) == true ? val : null;
    }

    /// <summary>
    /// RecursivePatchConf is a wrapper around protobuf message Protoconf.RecursivePatchConf.
    /// </summary>
    public class RecursivePatchConf : Messager, IMessagerName
    {
        private Protoconf.RecursivePatchConf _data = new();

        /// <summary>
        /// Name returns the RecursivePatchConf's message name.
        /// </summary>
        public string Name() => Protoconf.RecursivePatchConf.Descriptor.Name;

        /// <summary>
        /// Load loads RecursivePatchConf's content in the given dir, based on format and messager options.
        /// </summary>
        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.RecursivePatchConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.RecursivePatchConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception ex)
            {
                if (string.IsNullOrEmpty(Util.GetErrMsg()))
                {
                    Util.SetErrMsg($"failed to load RecursivePatchConf: {ex.Message}");
                }
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        /// <summary>
        /// Data returns the RecursivePatchConf's inner message data.
        /// </summary>
        public ref readonly Protoconf.RecursivePatchConf Data() => ref _data;

        /// <summary>
        /// Message returns the RecursivePatchConf's inner message data.
        /// </summary>
        public override pb::IMessage? Message() => _data;

        /// <summary>
        /// Get1 finds value in the 1st-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.RecursivePatchConf.Types.Shop? Get1(uint shopId) =>
            _data.ShopMap?.TryGetValue(shopId, out var val) == true ? val : null;

        /// <summary>
        /// Get2 finds value in the 2nd-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.RecursivePatchConf.Types.Shop.Types.Goods? Get2(uint shopId, uint goodsId) =>
            Get1(shopId)?.GoodsMap?.TryGetValue(goodsId, out var val) == true ? val : null;

        /// <summary>
        /// Get3 finds value in the 3rd-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public Protoconf.RecursivePatchConf.Types.Shop.Types.Goods.Types.Currency? Get3(uint shopId, uint goodsId, uint type) =>
            Get2(shopId, goodsId)?.CurrencyMap?.TryGetValue(type, out var val) == true ? val : null;

        /// <summary>
        /// Get4 finds value in the 4th-level map.
        /// It will return null if the key is not found.
        /// </summary>
        public int? Get4(uint shopId, uint goodsId, uint type, int key4) =>
            Get3(shopId, goodsId, type)?.ValueList?.TryGetValue(key4, out var val) == true ? val : null;
    }
}
