// Code generated by protoc-gen-csharp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-csharp-tableau-loader v0.1.0
// - protoc                           v3.19.3
// source: test_conf.proto
using System;
using System.Collections.Generic;
using Google.Protobuf;
using Google.Protobuf.Collections;

namespace Tableau
{
    public class ActivityConf : Messager, IMessagerName
    {
        private Protoconf.ActivityConf Data_ = new Protoconf.ActivityConf();

        public static string Name() => Protoconf.ActivityConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, LoadOptions? options = null)
        {
            var start = DateTime.Now;
            bool loaded = LoadMessageByPath<Protoconf.ActivityConf>(out var msg, dir, fmt, options);
            Data_ = msg;
            bool ok = loaded ? ProcessAfterLoad() : false;
            LoadStats.Duration = DateTime.Now - start;
            return ok;
        }

        public ref readonly Protoconf.ActivityConf Data() => ref Data_;

        public Protoconf.ActivityConf.Types.Activity? Get1(ulong activityId)
        {
            if (Data_.ActivityMap.TryGetValue(activityId, out var val))
            {
                return val;
            }
            return null;
        }

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? Get2(ulong activityId, uint chapterId)
        {
            var conf = Get1(activityId);
            if (conf?.ChapterMap != null && conf.ChapterMap.TryGetValue(chapterId, out var val))
            {
                return val;
            }
            return null;
        }

        public Protoconf.Section? Get3(ulong activityId, uint chapterId, uint sectionId)
        {
            var conf = Get2(activityId, chapterId);
            if (conf?.SectionMap != null && conf.SectionMap.TryGetValue(sectionId, out var val))
            {
                return val;
            }
            return null;
        }

        public int? Get4(ulong activityId, uint chapterId, uint sectionId, uint key4)
        {
            var conf = Get3(activityId, chapterId, sectionId);
            if (conf?.SectionRankMap != null && conf.SectionRankMap.TryGetValue(key4, out var val))
            {
                return val;
            }
            return null;
        }
    }


    public class ChapterConf : Messager, IMessagerName
    {
        private Protoconf.ChapterConf Data_ = new Protoconf.ChapterConf();

        public static string Name() => Protoconf.ChapterConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, LoadOptions? options = null)
        {
            var start = DateTime.Now;
            bool loaded = LoadMessageByPath<Protoconf.ChapterConf>(out var msg, dir, fmt, options);
            Data_ = msg;
            bool ok = loaded ? ProcessAfterLoad() : false;
            LoadStats.Duration = DateTime.Now - start;
            return ok;
        }

        public ref readonly Protoconf.ChapterConf Data() => ref Data_;

        public Protoconf.ChapterConf.Types.Chapter? Get1(ulong id)
        {
            if (Data_.ChapterMap.TryGetValue(id, out var val))
            {
                return val;
            }
            return null;
        }
    }

    public class ThemeConf : Messager, IMessagerName
    {
        private Protoconf.ThemeConf Data_ = new Protoconf.ThemeConf();

        public static string Name() => Protoconf.ThemeConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, LoadOptions? options = null)
        {
            var start = DateTime.Now;
            bool loaded = LoadMessageByPath<Protoconf.ThemeConf>(out var msg, dir, fmt, options);
            Data_ = msg;
            bool ok = loaded ? ProcessAfterLoad() : false;
            LoadStats.Duration = DateTime.Now - start;
            return ok;
        }

        public ref readonly Protoconf.ThemeConf Data() => ref Data_;

        public Protoconf.ThemeConf.Types.Theme? Get1(string name)
        {
            if (Data_.ThemeMap.TryGetValue(name, out var val))
            {
                return val;
            }
            return null;
        }

        public string? Get2(string name, string param)
        {
            var conf = Get1(name);
            if (conf?.ParamMap != null && conf.ParamMap.TryGetValue(param, out var val))
            {
                return val;
            }
            return null;
        }
    }
}
