// <auto-generated>
// Code generated by protoc-gen-csharp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-csharp-tableau-loader v0.1.0
// - protoc                           v3.19.3
// source: test_conf.proto
// </auto-generated>
#nullable enable
using pb = global::Google.Protobuf;
namespace Tableau
{
    public class ActivityConf : Messager, IMessagerName
    {
        // OrderedMap types.
        public class OrderedMap_int32Map : SortedDictionary<uint, int>;

        public class OrderedMap_protoconf_SectionValue(OrderedMap_int32Map item1, Protoconf.Section item2)
            : Tuple<OrderedMap_int32Map, Protoconf.Section>(item1, item2);
        public class OrderedMap_protoconf_SectionMap : SortedDictionary<uint, OrderedMap_protoconf_SectionValue>;

        public class OrderedMap_Activity_ChapterValue(OrderedMap_protoconf_SectionMap item1, Protoconf.ActivityConf.Types.Activity.Types.Chapter item2)
            : Tuple<OrderedMap_protoconf_SectionMap, Protoconf.ActivityConf.Types.Activity.Types.Chapter>(item1, item2);
        public class OrderedMap_Activity_ChapterMap : SortedDictionary<uint, OrderedMap_Activity_ChapterValue>;

        public class OrderedMap_ActivityValue(OrderedMap_Activity_ChapterMap item1, Protoconf.ActivityConf.Types.Activity item2)
            : Tuple<OrderedMap_Activity_ChapterMap, Protoconf.ActivityConf.Types.Activity>(item1, item2);
        public class OrderedMap_ActivityMap : SortedDictionary<ulong, OrderedMap_ActivityValue>;

        private OrderedMap_ActivityMap _orderedMap = [];


        // LevelIndex keys.
        public readonly struct LevelIndex_Activity_ChapterKey : IEquatable<LevelIndex_Activity_ChapterKey>
        {
            public ulong ActivityId { get; }
            public uint ChapterId { get; }

            public LevelIndex_Activity_ChapterKey(ulong activityId, uint chapterId)
            {
                ActivityId = activityId;
                ChapterId = chapterId;
            }

            public bool Equals(LevelIndex_Activity_ChapterKey other) =>
                (ActivityId, ChapterId).Equals((other.ActivityId, other.ChapterId));

            public override int GetHashCode() =>
                (ActivityId, ChapterId).GetHashCode();
        }

        // Index types.
        // Index: ActivityName
        public class Index_ActivityMap : Dictionary<string, List<Protoconf.ActivityConf.Types.Activity>>;

        private Index_ActivityMap _indexActivityMap = [];

        // Index: ChapterID
        public class Index_ChapterMap : Dictionary<uint, List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>>;

        private Index_ChapterMap _indexChapterMap = [];

        private Dictionary<ulong, Index_ChapterMap> _indexChapterMap1 = [];

        // Index: ChapterName<AwardID>@NamedChapter
        public class Index_NamedChapterMap : Dictionary<string, List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>>;

        private Index_NamedChapterMap _indexNamedChapterMap = [];

        private Dictionary<ulong, Index_NamedChapterMap> _indexNamedChapterMap1 = [];

        // Index: SectionItemID@Award
        public class Index_AwardMap : Dictionary<uint, List<Protoconf.Section.Types.SectionItem>>;

        private Index_AwardMap _indexAwardMap = [];

        private Dictionary<ulong, Index_AwardMap> _indexAwardMap1 = [];

        private Dictionary<LevelIndex_Activity_ChapterKey, Index_AwardMap> _indexAwardMap2 = [];

        private Protoconf.ActivityConf _data = new();

        public static string Name() => Protoconf.ActivityConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.ActivityConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.ActivityConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.ActivityConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        protected override bool ProcessAfterLoad()
        {
            // OrderedMap init.
            _orderedMap.Clear();
            foreach (var (key1, value1) in _data.ActivityMap)
            {
                var ordered_map1 = new OrderedMap_Activity_ChapterMap();
                foreach (var (key2, value2) in value1.ChapterMap)
                {
                    var ordered_map2 = new OrderedMap_protoconf_SectionMap();
                    foreach (var (key3, value3) in value2.SectionMap)
                    {
                        var ordered_map3 = new OrderedMap_int32Map();
                        foreach (var (key4, value4) in value3.SectionRankMap)
                        {
                            ordered_map3[key4] = value4;
                        }
                        ordered_map2[key3] = new OrderedMap_protoconf_SectionValue(ordered_map3, value3);
                    }
                    ordered_map1[key2] = new OrderedMap_Activity_ChapterValue(ordered_map2, value2);
                }
                _orderedMap[key1] = new OrderedMap_ActivityValue(ordered_map1, value1);
            }
            // Index init.
            _indexActivityMap.Clear();
            _indexChapterMap.Clear();
            _indexChapterMap1.Clear();
            _indexNamedChapterMap.Clear();
            _indexNamedChapterMap1.Clear();
            _indexAwardMap.Clear();
            _indexAwardMap1.Clear();
            _indexAwardMap2.Clear();
            foreach (var item1 in _data.ActivityMap)
            {
                var k1 = item1.Key;
                {
                    // Index: ActivityName
                    var key = item1.Value.ActivityName;
                    {
                        var list = _indexActivityMap.TryGetValue(key, out var existingList) ?
                        existingList : _indexActivityMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
                foreach (var item2 in item1.Value.ChapterMap)
                {
                    var k2 = item2.Key;
                    {
                        // Index: ChapterID
                        var key = item2.Value.ChapterId;
                        {
                            var list = _indexChapterMap.TryGetValue(key, out var existingList) ?
                            existingList : _indexChapterMap[key] = [];
                            list.Add(item2.Value);
                        }
                        {
                            var map = _indexChapterMap1.TryGetValue(k1, out var existingMap) ?
                            existingMap : _indexChapterMap1[k1] = [];
                            var list = map.TryGetValue(key, out var existingList) ?
                            existingList : map[key] = [];
                            list.Add(item2.Value);
                        }
                    }
                    {
                        // Index: ChapterName<AwardID>@NamedChapter
                        var key = item2.Value.ChapterName;
                        {
                            var list = _indexNamedChapterMap.TryGetValue(key, out var existingList) ?
                            existingList : _indexNamedChapterMap[key] = [];
                            list.Add(item2.Value);
                        }
                        {
                            var map = _indexNamedChapterMap1.TryGetValue(k1, out var existingMap) ?
                            existingMap : _indexNamedChapterMap1[k1] = [];
                            var list = map.TryGetValue(key, out var existingList) ?
                            existingList : map[key] = [];
                            list.Add(item2.Value);
                        }
                    }
                    foreach (var item3 in item2.Value.SectionMap)
                    {
                        var k3 = item3.Key;
                        foreach (var item4 in item3.Value.SectionItemList)
                        {
                            {
                                // Index: SectionItemID@Award
                                var key = item4.Id;
                                {
                                    var list = _indexAwardMap.TryGetValue(key, out var existingList) ?
                                    existingList : _indexAwardMap[key] = [];
                                    list.Add(item4);
                                }
                                {
                                    var map = _indexAwardMap1.TryGetValue(k1, out var existingMap) ?
                                    existingMap : _indexAwardMap1[k1] = [];
                                    var list = map.TryGetValue(key, out var existingList) ?
                                    existingList : map[key] = [];
                                    list.Add(item4);
                                }
                                {
                                    var mapKey = new LevelIndex_Activity_ChapterKey(k1, k2);
                                    var map = _indexAwardMap2.TryGetValue(mapKey, out var existingMap) ?
                                    existingMap : _indexAwardMap2[mapKey] = [];
                                    var list = map.TryGetValue(key, out var existingList) ?
                                    existingList : map[key] = [];
                                    list.Add(item4);
                                }
                            }
                        }
                    }
                }
            }
            // Index(sort): ChapterName<AwardID>@NamedChapter
            Comparison<Protoconf.ActivityConf.Types.Activity.Types.Chapter> indexNamedChapterMapComparison = (a, b) =>
                (a.AwardId).CompareTo((b.AwardId));
            foreach (var itemList in _indexNamedChapterMap.Values)
            {
                itemList.Sort(indexNamedChapterMapComparison);
            }
            foreach (var itemDict in _indexNamedChapterMap1.Values)
            {
                foreach (var itemList in itemDict.Values)
                {
                    itemList.Sort(indexNamedChapterMapComparison);
                }
            }
            return true;
        }

        public Protoconf.ActivityConf.Types.Activity? Get1(ulong activityId) =>
            _data.ActivityMap?.TryGetValue(activityId, out var val) == true ? val : null;

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? Get2(ulong activityId, uint chapterId) =>
            Get1(activityId)?.ChapterMap?.TryGetValue(chapterId, out var val) == true ? val : null;

        public Protoconf.Section? Get3(ulong activityId, uint chapterId, uint sectionId) =>
            Get2(activityId, chapterId)?.SectionMap?.TryGetValue(sectionId, out var val) == true ? val : null;

        public int? Get4(ulong activityId, uint chapterId, uint sectionId, uint key4) =>
            Get3(activityId, chapterId, sectionId)?.SectionRankMap?.TryGetValue(key4, out var val) == true ? val : null;

        // OrderedMap accessers.
        public ref readonly OrderedMap_ActivityMap GetOrderedMap() => ref _orderedMap;

        public OrderedMap_Activity_ChapterMap? GetOrderedMap1(ulong activityId) =>
            _orderedMap.TryGetValue(activityId, out var value) ? value.Item1 : null;

        public OrderedMap_protoconf_SectionMap? GetOrderedMap2(ulong activityId, uint chapterId) =>
            GetOrderedMap1(activityId)?.TryGetValue(chapterId, out var value) == true ? value.Item1 : null;

        public OrderedMap_int32Map? GetOrderedMap3(ulong activityId, uint chapterId, uint sectionId) =>
            GetOrderedMap2(activityId, chapterId)?.TryGetValue(sectionId, out var value) == true ? value.Item1 : null;

        // Index: ActivityName
        public ref readonly Index_ActivityMap FindActivityMap() => ref _indexActivityMap;

        public List<Protoconf.ActivityConf.Types.Activity>? FindActivity(string activityName) =>
            _indexActivityMap.TryGetValue(activityName, out var value) ? value : null;

        public Protoconf.ActivityConf.Types.Activity? FindFirstActivity(string activityName) =>
            FindActivity(activityName)?.FirstOrDefault();

        // Index: ChapterID
        public ref readonly Index_ChapterMap FindChapterMap() => ref _indexChapterMap;

        public List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>? FindChapter(uint chapterId) =>
            _indexChapterMap.TryGetValue(chapterId, out var value) ? value : null;

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? FindFirstChapter(uint chapterId) =>
            FindChapter(chapterId)?.FirstOrDefault();

        public Index_ChapterMap? FindChapterMap1(ulong activityId) =>
            _indexChapterMap1.TryGetValue(activityId, out var value) ? value : null;

        public List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>? FindChapter1(ulong activityId, uint chapterId) =>
            FindChapterMap1(activityId)?.TryGetValue(chapterId, out var value) == true ? value : null;

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? FindFirstChapter1(ulong activityId, uint chapterId) =>
            FindChapter1(activityId, chapterId)?.FirstOrDefault();

        // Index: ChapterName<AwardID>@NamedChapter
        public ref readonly Index_NamedChapterMap FindNamedChapterMap() => ref _indexNamedChapterMap;

        public List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>? FindNamedChapter(string chapterName) =>
            _indexNamedChapterMap.TryGetValue(chapterName, out var value) ? value : null;

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? FindFirstNamedChapter(string chapterName) =>
            FindNamedChapter(chapterName)?.FirstOrDefault();

        public Index_NamedChapterMap? FindNamedChapterMap1(ulong activityId) =>
            _indexNamedChapterMap1.TryGetValue(activityId, out var value) ? value : null;

        public List<Protoconf.ActivityConf.Types.Activity.Types.Chapter>? FindNamedChapter1(ulong activityId, string chapterName) =>
            FindNamedChapterMap1(activityId)?.TryGetValue(chapterName, out var value) == true ? value : null;

        public Protoconf.ActivityConf.Types.Activity.Types.Chapter? FindFirstNamedChapter1(ulong activityId, string chapterName) =>
            FindNamedChapter1(activityId, chapterName)?.FirstOrDefault();

        // Index: SectionItemID@Award
        public ref readonly Index_AwardMap FindAwardMap() => ref _indexAwardMap;

        public List<Protoconf.Section.Types.SectionItem>? FindAward(uint id) =>
            _indexAwardMap.TryGetValue(id, out var value) ? value : null;

        public Protoconf.Section.Types.SectionItem? FindFirstAward(uint id) =>
            FindAward(id)?.FirstOrDefault();

        public Index_AwardMap? FindAwardMap1(ulong activityId) =>
            _indexAwardMap1.TryGetValue(activityId, out var value) ? value : null;

        public List<Protoconf.Section.Types.SectionItem>? FindAward1(ulong activityId, uint id) =>
            FindAwardMap1(activityId)?.TryGetValue(id, out var value) == true ? value : null;

        public Protoconf.Section.Types.SectionItem? FindFirstAward1(ulong activityId, uint id) =>
            FindAward1(activityId, id)?.FirstOrDefault();

        public Index_AwardMap? FindAwardMap2(ulong activityId, uint chapterId) =>
            _indexAwardMap2.TryGetValue(new LevelIndex_Activity_ChapterKey(activityId, chapterId), out var value) ? value : null;

        public List<Protoconf.Section.Types.SectionItem>? FindAward2(ulong activityId, uint chapterId, uint id) =>
            FindAwardMap2(activityId, chapterId)?.TryGetValue(id, out var value) == true ? value : null;

        public Protoconf.Section.Types.SectionItem? FindFirstAward2(ulong activityId, uint chapterId, uint id) =>
            FindAward2(activityId, chapterId, id)?.FirstOrDefault();
    }

    public class ChapterConf : Messager, IMessagerName
    {
        private Protoconf.ChapterConf _data = new();

        public static string Name() => Protoconf.ChapterConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.ChapterConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.ChapterConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.ChapterConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        public Protoconf.ChapterConf.Types.Chapter? Get1(ulong id) =>
            _data.ChapterMap?.TryGetValue(id, out var val) == true ? val : null;
    }

    public class ThemeConf : Messager, IMessagerName
    {
        private Protoconf.ThemeConf _data = new();

        public static string Name() => Protoconf.ThemeConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.ThemeConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.ThemeConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.ThemeConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        public Protoconf.ThemeConf.Types.Theme? Get1(string name) =>
            _data.ThemeMap?.TryGetValue(name, out var val) == true ? val : null;

        public string? Get2(string name, string param) =>
            Get1(name)?.ParamMap?.TryGetValue(param, out var val) == true ? val : null;
    }

    public class TaskConf : Messager, IMessagerName
    {
        // Index types.
        // Index: ActivityID<Goal,ID>
        public class Index_TaskMap : Dictionary<long, List<Protoconf.TaskConf.Types.Task>>;

        private Index_TaskMap _indexTaskMap = [];

        // OrderedIndex types.
        // OrderedIndex: Goal<ID>@OrderedTask
        public class OrderedIndex_OrderedTaskMap : SortedDictionary<long, List<Protoconf.TaskConf.Types.Task>>;

        private OrderedIndex_OrderedTaskMap _orderedIndexOrderedTaskMap = [];

        // OrderedIndex: Expiry@TaskExpiry
        public class OrderedIndex_TaskExpiryMap : SortedDictionary<long, List<Protoconf.TaskConf.Types.Task>>;

        private OrderedIndex_TaskExpiryMap _orderedIndexTaskExpiryMap = [];

        // OrderedIndex: Expiry<Goal,ID>@SortedTaskExpiry
        public class OrderedIndex_SortedTaskExpiryMap : SortedDictionary<long, List<Protoconf.TaskConf.Types.Task>>;

        private OrderedIndex_SortedTaskExpiryMap _orderedIndexSortedTaskExpiryMap = [];

        // OrderedIndex: (Expiry,ActivityID)@ActivityExpiry
        public readonly struct OrderedIndex_ActivityExpiryKey : IComparable<OrderedIndex_ActivityExpiryKey>
        {
            public long Expiry { get; }
            public long ActivityId { get; }

            public OrderedIndex_ActivityExpiryKey(long expiry, long activityId)
            {
                Expiry = expiry;
                ActivityId = activityId;
            }

            public int CompareTo(OrderedIndex_ActivityExpiryKey other) =>
                (Expiry, ActivityId).CompareTo((other.Expiry, other.ActivityId));
        }

        public class OrderedIndex_ActivityExpiryMap : SortedDictionary<OrderedIndex_ActivityExpiryKey, List<Protoconf.TaskConf.Types.Task>>;

        private OrderedIndex_ActivityExpiryMap _orderedIndexActivityExpiryMap = [];

        private Protoconf.TaskConf _data = new();

        public static string Name() => Protoconf.TaskConf.Descriptor.Name;

        public override bool Load(string dir, Format fmt, in Load.MessagerOptions? options = null)
        {
            var start = DateTime.Now;
            try
            {
                _data = (Protoconf.TaskConf)(
                    Tableau.Load.LoadMessagerInDir(Protoconf.TaskConf.Descriptor, dir, fmt, options)
                    ?? throw new InvalidOperationException()
                );
            }
            catch (Exception)
            {
                return false;
            }
            LoadStats.Duration = DateTime.Now - start;
            return ProcessAfterLoad();
        }

        public ref readonly Protoconf.TaskConf Data() => ref _data;

        public override pb::IMessage? Message() => _data;

        protected override bool ProcessAfterLoad()
        {
            // Index init.
            _indexTaskMap.Clear();
            foreach (var item1 in _data.TaskMap)
            {
                var k1 = item1.Key;
                {
                    // Index: ActivityID<Goal,ID>
                    var key = item1.Value.ActivityId;
                    {
                        var list = _indexTaskMap.TryGetValue(key, out var existingList) ?
                        existingList : _indexTaskMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
            }
            // Index(sort): ActivityID<Goal,ID>
            Comparison<Protoconf.TaskConf.Types.Task> indexTaskMapComparison = (a, b) =>
                (a.Goal, a.Id).CompareTo((b.Goal, b.Id));
            foreach (var itemList in _indexTaskMap.Values)
            {
                itemList.Sort(indexTaskMapComparison);
            }
            // OrderedIndex init.
            _orderedIndexOrderedTaskMap.Clear();
            _orderedIndexTaskExpiryMap.Clear();
            _orderedIndexSortedTaskExpiryMap.Clear();
            _orderedIndexActivityExpiryMap.Clear();
            foreach (var item1 in _data.TaskMap)
            {
                var k1 = item1.Key;
                {
                    // OrderedIndex: Goal<ID>@OrderedTask
                    var key = item1.Value.Goal;
                    {
                        var list = _orderedIndexOrderedTaskMap.TryGetValue(key, out var existingList) ?
                        existingList : _orderedIndexOrderedTaskMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
                {
                    // OrderedIndex: Expiry@TaskExpiry
                    var key = item1.Value.Expiry?.Seconds ?? 0;
                    {
                        var list = _orderedIndexTaskExpiryMap.TryGetValue(key, out var existingList) ?
                        existingList : _orderedIndexTaskExpiryMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
                {
                    // OrderedIndex: Expiry<Goal,ID>@SortedTaskExpiry
                    var key = item1.Value.Expiry?.Seconds ?? 0;
                    {
                        var list = _orderedIndexSortedTaskExpiryMap.TryGetValue(key, out var existingList) ?
                        existingList : _orderedIndexSortedTaskExpiryMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
                {
                    // OrderedIndex: (Expiry,ActivityID)@ActivityExpiry
                    var key = new OrderedIndex_ActivityExpiryKey(item1.Value.Expiry?.Seconds ?? 0, item1.Value.ActivityId);
                    {
                        var list = _orderedIndexActivityExpiryMap.TryGetValue(key, out var existingList) ?
                        existingList : _orderedIndexActivityExpiryMap[key] = [];
                        list.Add(item1.Value);
                    }
                }
            }
            // OrderedIndex(sort): Goal<ID>@OrderedTask
            Comparison<Protoconf.TaskConf.Types.Task> orderedIndexOrderedTaskMapComparison = (a, b) =>
                (a.Id).CompareTo((b.Id));
            foreach (var itemList in _orderedIndexOrderedTaskMap.Values)
            {
                itemList.Sort(orderedIndexOrderedTaskMapComparison);
            }
            // OrderedIndex(sort): Expiry<Goal,ID>@SortedTaskExpiry
            Comparison<Protoconf.TaskConf.Types.Task> orderedIndexSortedTaskExpiryMapComparison = (a, b) =>
                (a.Goal, a.Id).CompareTo((b.Goal, b.Id));
            foreach (var itemList in _orderedIndexSortedTaskExpiryMap.Values)
            {
                itemList.Sort(orderedIndexSortedTaskExpiryMapComparison);
            }
            return true;
        }

        public Protoconf.TaskConf.Types.Task? Get1(long id) =>
            _data.TaskMap?.TryGetValue(id, out var val) == true ? val : null;

        // Index: ActivityID<Goal,ID>
        public ref readonly Index_TaskMap FindTaskMap() => ref _indexTaskMap;

        public List<Protoconf.TaskConf.Types.Task>? FindTask(long activityId) =>
            _indexTaskMap.TryGetValue(activityId, out var value) ? value : null;

        public Protoconf.TaskConf.Types.Task? FindFirstTask(long activityId) =>
            FindTask(activityId)?.FirstOrDefault();

        // OrderedIndex: Goal<ID>@OrderedTask
        public ref readonly OrderedIndex_OrderedTaskMap FindOrderedTaskMap() => ref _orderedIndexOrderedTaskMap;

        public List<Protoconf.TaskConf.Types.Task>? FindOrderedTask(long goal) =>
            _orderedIndexOrderedTaskMap.TryGetValue(goal, out var value) ? value : null;

        public Protoconf.TaskConf.Types.Task? FindFirstOrderedTask(long goal) =>
            FindOrderedTask(goal)?.FirstOrDefault();

        // OrderedIndex: Expiry@TaskExpiry
        public ref readonly OrderedIndex_TaskExpiryMap FindTaskExpiryMap() => ref _orderedIndexTaskExpiryMap;

        public List<Protoconf.TaskConf.Types.Task>? FindTaskExpiry(long expiry) =>
            _orderedIndexTaskExpiryMap.TryGetValue(expiry, out var value) ? value : null;

        public Protoconf.TaskConf.Types.Task? FindFirstTaskExpiry(long expiry) =>
            FindTaskExpiry(expiry)?.FirstOrDefault();

        // OrderedIndex: Expiry<Goal,ID>@SortedTaskExpiry
        public ref readonly OrderedIndex_SortedTaskExpiryMap FindSortedTaskExpiryMap() => ref _orderedIndexSortedTaskExpiryMap;

        public List<Protoconf.TaskConf.Types.Task>? FindSortedTaskExpiry(long expiry) =>
            _orderedIndexSortedTaskExpiryMap.TryGetValue(expiry, out var value) ? value : null;

        public Protoconf.TaskConf.Types.Task? FindFirstSortedTaskExpiry(long expiry) =>
            FindSortedTaskExpiry(expiry)?.FirstOrDefault();

        // OrderedIndex: (Expiry,ActivityID)@ActivityExpiry
        public ref readonly OrderedIndex_ActivityExpiryMap FindActivityExpiryMap() => ref _orderedIndexActivityExpiryMap;

        public List<Protoconf.TaskConf.Types.Task>? FindActivityExpiry(long expiry, long activityId) =>
            _orderedIndexActivityExpiryMap.TryGetValue(new OrderedIndex_ActivityExpiryKey(expiry, activityId), out var value) ? value : null;

        public Protoconf.TaskConf.Types.Task? FindFirstActivityExpiry(long expiry, long activityId) =>
            FindActivityExpiry(expiry, activityId)?.FirstOrDefault();
    }
}
