package helper

import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"
	"github.com/tableauio/tableau/proto/tableaupb"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func GenerateFileHeader(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, version string) {
	GenerateCommonHeader(gen, g, version)
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
}

func GenerateCommonHeader(gen *protogen.Plugin, g *protogen.GeneratedFile, version string) {
	g.P("// Code generated by protoc-gen-cpp-tableau-loader. DO NOT EDIT.")
	g.P("// versions:")
	g.P("// - protoc-gen-cpp-tableau-loader v", version)
	g.P("// - protoc                        ", protocVersion(gen))
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

func ParseCppFieldName(fd protoreflect.FieldDescriptor) string {
	return escapeIdentifier(string(fd.Name()))
}

func ParseMapFieldName(fd protoreflect.FieldDescriptor) string {
	opts := fd.Options().(*descriptorpb.FieldOptions)
	fdOpts := proto.GetExtension(opts, tableaupb.E_Field).(*tableaupb.FieldOptions)
	name := fdOpts.GetKey()
	if fd.MapValue().Kind() == protoreflect.MessageKind {
		valueFd := fd.MapValue().Message().Fields().Get(0)
		name = string(valueFd.Name())
	}
	return escapeIdentifier(name)
}

func ParseIndexFieldNameAsFuncParam(fd protoreflect.FieldDescriptor) string {
	if fd.IsList() {
		opts := fd.Options().(*descriptorpb.FieldOptions)
		fdOpts := proto.GetExtension(opts, tableaupb.E_Field).(*tableaupb.FieldOptions)
		return escapeIdentifier(strcase.ToSnake(fdOpts.GetName()))
	}
	return ParseCppFieldName(fd)
}

// ParseCppType converts a FieldDescriptor to C++ type string.
func ParseCppType(fd protoreflect.FieldDescriptor) string {
	switch fd.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.EnumKind:
		protoFullName := string(fd.Enum().FullName())
		return strings.ReplaceAll(protoFullName, ".", "::")
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32_t"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32_t"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64_t"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64_t"
	case protoreflect.FloatKind:
		return "float"
	case protoreflect.DoubleKind:
		return "double"
	case protoreflect.StringKind, protoreflect.BytesKind:
		return "std::string"
	case protoreflect.MessageKind:
		return ParseCppClassType(fd.Message())
	// case protoreflect.GroupKind:
	// 	return "group"
	default:
		return fmt.Sprintf("<unknown:%d>", fd.Kind())
	}
}

// ParseMapKeyType converts a FieldDescriptor to its map key type.
// fd must be an comparable type.
func ParseMapKeyType(fd protoreflect.FieldDescriptor) string {
	switch fd.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind, protoreflect.EnumKind:
		return "int32_t"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32_t"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64_t"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64_t"
	case protoreflect.FloatKind:
		return "float"
	case protoreflect.DoubleKind:
		return "double"
	case protoreflect.StringKind:
		return "std::string"
	default:
		panic(fmt.Sprintf("unsupported kind: %d", fd.Kind()))
	}
}

// ParseOrderedIndexKeyType converts a FieldDescriptor to its treemap key type.
// fd must be an ordered type, or a message which can be converted to an ordered type.
func ParseOrderedIndexKeyType(fd protoreflect.FieldDescriptor) string {
	switch fd.Kind() {
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32_t"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32_t"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64_t"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64_t"
	case protoreflect.FloatKind:
		return "float"
	case protoreflect.DoubleKind:
		return "double"
	case protoreflect.StringKind:
		return "std::string"
	case protoreflect.EnumKind:
		protoFullName := string(fd.Enum().FullName())
		return strings.ReplaceAll(protoFullName, ".", "::")
	case protoreflect.MessageKind:
		switch fd.Message().FullName() {
		case "google.protobuf.Timestamp", "google.protobuf.Duration":
			return "int64_t"
		default:
		}
		fallthrough
	default:
		panic(fmt.Sprintf("unsupported kind: %d", fd.Kind()))
	}
}

func ToConstRefType(cpptype string) string {
	if cpptype == "std::string" {
		return "const std::string&"
	}
	return cpptype
}

func ParseCppClassType(md protoreflect.MessageDescriptor) string {
	protoFullName := string(md.FullName())
	return strings.ReplaceAll(protoFullName, ".", "::")
}

func ParseLeveledMapPrefix(md protoreflect.MessageDescriptor, mapFd protoreflect.FieldDescriptor) string {
	if mapFd.MapValue().Kind() == protoreflect.MessageKind {
		localMsgProtoName := strings.TrimPrefix(string(mapFd.MapValue().Message().FullName()), string(md.FullName())+".")
		return strings.ReplaceAll(localMsgProtoName, ".", "_")
	}
	return mapFd.MapValue().Kind().String()
}

type MapKey struct {
	Type          string
	Name          string
	FieldName     string                       // multi-column index only (may be deduplicated, e.g., "Id" → "Id3")
	OrigFieldName string                       // original FieldName before deduplication (empty if not renamed)
	Fd            protoreflect.FieldDescriptor // the map field descriptor this key belongs to
}

type MapKeySlice []MapKey

// AddMapKey appends a new map key to the slice, automatically deduplicating
// both Name (used as function parameter names) and FieldName (used as struct
// field names in LevelIndex key structs).
//
// Deduplication is needed because different map levels may share the same key
// name. For example, given the following nested proto maps where country_map
// and item_map both use "ID" as their key name:
//
//	message Fruit4Conf {
//	    map<int32, Fruit> fruit_map = 1;          // key field: "FruitType"
//	    message Fruit {
//	        map<int32, Country> country_map = 2;  // key field: "ID"
//	        message Country {
//	            map<int32, Item> item_map = 3;    // key field: "ID"  ← same name!
//	        }
//	    }
//	}
//
// Without dedup, the generated LevelIndex key struct would have duplicate
// field names, causing a compile error:
//
//	struct LevelIndex_Fruit_Country_ItemKey {
//	    int32_t id;        // key of protoconf.Fruit4Conf.fruit_map
//	    int32_t id;        // key of protoconf.Fruit4Conf.Fruit.country_map
//	    int32_t id;        // key of protoconf.Fruit4Conf.Fruit.Country.item_map — COMPILE ERROR!
//	};
//
// With dedup, the conflicting name gets a numeric suffix (the 1-based position
// of the new key in the slice), producing valid C++ code:
//
//	struct LevelIndex_Fruit_Country_ItemKey {
//	    int32_t fruit_type; // key of protoconf.Fruit4Conf.fruit_map
//	    int32_t id;         // key of protoconf.Fruit4Conf.Fruit.country_map
//	    int32_t id3;        // key of protoconf.Fruit4Conf.Fruit.Country.item_map (renamed from id)
//	};
func (s MapKeySlice) AddMapKey(newKey MapKey) MapKeySlice {
	if newKey.Name == "" {
		newKey.Name = fmt.Sprintf("key%d", len(s)+1)
	}
	// Deduplicate Name (used as function parameter, e.g., "id" → "id3").
	for _, key := range s {
		if key.Name == newKey.Name {
			newKey.Name = fmt.Sprintf("%s%d", newKey.Name, len(s)+1)
			break
		}
	}
	// Deduplicate FieldName (used as struct field, e.g., "Id" → "Id3").
	// This is only relevant for multi-column indexes that generate LevelIndex
	// key structs; single-column indexes leave FieldName empty.
	if newKey.FieldName != "" {
		for _, key := range s {
			if key.FieldName == newKey.FieldName {
				newKey.OrigFieldName = newKey.FieldName
				newKey.FieldName = fmt.Sprintf("%s%d", newKey.FieldName, len(s)+1)
				break
			}
		}
	}
	return append(s, newKey)
}

// GenGetParams generates function parameters, which are the names listed in the function's definition.
func (s MapKeySlice) GenGetParams() string {
	var params []string
	for _, key := range s {
		params = append(params, ToConstRefType(key.Type)+" "+key.Name)
	}
	return strings.Join(params, ", ")
}

// GenGetArguments generates function arguments, which are the real values passed to the function.
func (s MapKeySlice) GenGetArguments() string {
	var params []string
	for _, key := range s {
		params = append(params, key.Name)
	}
	return strings.Join(params, ", ")
}

// GenOtherArguments generates function arguments for other value of std::tie.
func (s MapKeySlice) GenOtherArguments(other string) string {
	var params []string
	for _, key := range s {
		params = append(params, other+"."+key.Name)
	}
	return strings.Join(params, ", ")
}

func Indent(depth int) string {
	return strings.Repeat("  ", depth)
}

func Whitespace(count int) string {
	return strings.Repeat(" ", count)
}

func ParseMapValueType(fd protoreflect.FieldDescriptor) string {
	valueType := ParseCppType(fd.MapValue())
	if fd.MapValue().Kind() == protoreflect.MessageKind {
		return "const " + valueType + "*"
	}
	return valueType
}
