// Code generated by protoc-gen-go-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-loader v0.2.5
// - protoc                       v3.19.3

package code

type Code int

const (
	Success Code = iota
	NotFound
	Nil
	Unknown
)
