// @generated by protoc-gen-ts-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-ts-tableau-loader v0.1.0
// - protoc                (unknown)
/* eslint-disable */

// Barrel for proto package "protoconf": re-exports every protobuf-es
// generated module of this package, so loaders import the whole package
// under one namespace alias (import * as protoconf), matching the
// package-qualified naming used by loaders of other languages.

export * from "../../protoconf/common_conf_pb.js";
export * from "../../protoconf/hero_conf_pb.js";
export * from "../../protoconf/index_conf_pb.js";
export * from "../../protoconf/item_conf_pb.js";
export * from "../../protoconf/patch_conf_pb.js";
export * from "../../protoconf/test_conf_pb.js";
export * from "../../protoconf/union_conf_pb.js";
