// @generated by protoc-gen-ts-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-ts-tableau-loader v0.1.0
// - protoc                (unknown)
// source: hero_conf.proto
/* eslint-disable */

import { create } from "@bufbuild/protobuf";
import { Messager } from "./messager.pc.js";
import { Format } from "./util.pc.js";
import { loadMessagerInDir, type MessagerOptions } from "./load.pc.js";
import * as protoconf from "./barrel/protoconf.pc.js";
import * as base from "./barrel/base.pc.js";

/**
 * HeroConf is a wrapper around protobuf message protoconf.HeroConf.
 */
export class HeroConf extends Messager {
  #data: protoconf.HeroConf = create(protoconf.HeroConfSchema);

  /** name returns the HeroConf's message name. */
  name(): string {
    return protoconf.HeroConfSchema.name;
  }

  /** load loads HeroConf's content in the given dir, based on format and messager options. Throws on failure. */
  load(dir: string, fmt: Format, options?: MessagerOptions): void {
    const start = Date.now();
    try {
      this.#data = loadMessagerInDir(protoconf.HeroConfSchema, dir, fmt, options);
    } catch (e) {
      throw new Error(`failed to load HeroConf`, { cause: e });
    }
    this.loadStats.durationMs = Date.now() - start;
    this.processAfterLoad();
  }

  /** data returns the HeroConf's inner message data. */
  data(): protoconf.HeroConf {
    return this.#data;
  }

  /** message returns the HeroConf's inner message data. */
  override message(): protoconf.HeroConf {
    return this.#data;
  }

  /** get1 finds value in the 1st-level map; returns undefined if not found. */
  get1(name: string): protoconf.HeroConf_Hero | undefined {
    return this.#data.heroMap[name];
  }

  /** get2 finds value in the 2nd-level map; returns undefined if not found. */
  get2(name: string, title: string): protoconf.HeroConf_Hero_Attr | undefined {
    return this.get1(name)?.attrMap[title];
  }
}

/**
 * HeroBaseConf is a wrapper around protobuf message protoconf.HeroBaseConf.
 */
export class HeroBaseConf extends Messager {
  #data: protoconf.HeroBaseConf = create(protoconf.HeroBaseConfSchema);

  /** name returns the HeroBaseConf's message name. */
  name(): string {
    return protoconf.HeroBaseConfSchema.name;
  }

  /** load loads HeroBaseConf's content in the given dir, based on format and messager options. Throws on failure. */
  load(dir: string, fmt: Format, options?: MessagerOptions): void {
    const start = Date.now();
    try {
      this.#data = loadMessagerInDir(protoconf.HeroBaseConfSchema, dir, fmt, options);
    } catch (e) {
      throw new Error(`failed to load HeroBaseConf`, { cause: e });
    }
    this.loadStats.durationMs = Date.now() - start;
    this.processAfterLoad();
  }

  /** data returns the HeroBaseConf's inner message data. */
  data(): protoconf.HeroBaseConf {
    return this.#data;
  }

  /** message returns the HeroBaseConf's inner message data. */
  override message(): protoconf.HeroBaseConf {
    return this.#data;
  }

  /** get1 finds value in the 1st-level map; returns undefined if not found. */
  get1(name: string): base.Hero | undefined {
    return this.#data.heroMap[name];
  }

  /** get2 finds value in the 2nd-level map; returns undefined if not found. */
  get2(name: string, id: string): base.Item | undefined {
    return this.get1(name)?.itemMap[id];
  }
}
