// @generated by protoc-gen-ts-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-ts-tableau-loader v0.1.0
// - protoc                (unknown)
/* eslint-disable */

import { clone, getExtension, type DescField, type DescMessage, type Message } from "@bufbuild/protobuf";
import * as tableaupb from "../protoconf/tableau/protobuf/tableau_pb.js";

/**
 * Format specifies the format of the configuration file.
 */
export enum Format {
  UNKNOWN = "unknown",
  JSON = "json",
  BIN = "bin",
}

const UNKNOWN_EXT = ".unknown";
const JSON_EXT = ".json";
const BIN_EXT = ".binpb";

/**
 * getFormat returns the Format determined by the file extension of the given path.
 */
export function getFormat(path: string): Format {
  if (path.endsWith(JSON_EXT)) return Format.JSON;
  if (path.endsWith(BIN_EXT)) return Format.BIN;
  return Format.UNKNOWN;
}

/**
 * format2Ext returns the file extension corresponding to the given format.
 */
export function format2Ext(fmt: Format): string {
  switch (fmt) {
    case Format.JSON:
      return JSON_EXT;
    case Format.BIN:
      return BIN_EXT;
    default:
      return UNKNOWN_EXT;
  }
}

// AnyMessage is a structural view over a protobuf-es message used by the
// reflection-based patch routines below.
type AnyMessage = Record<string, unknown>;

/**
 * getSheetPatch returns the sheet-level patch type for a message descriptor.
 */
export function getSheetPatch(desc: DescMessage): tableaupb.Patch {
  const opts = desc.proto.options;
  if (!opts) return tableaupb.Patch.NONE;
  const ws = getExtension(opts, tableaupb.worksheet);
  return ws?.patch ?? tableaupb.Patch.NONE;
}

function getFieldPatch(fd: DescField): tableaupb.Patch {
  const opts = fd.proto.options;
  if (!opts) return tableaupb.Patch.NONE;
  const fieldOpts = getExtension(opts, tableaupb.field);
  return fieldOpts?.prop?.patch ?? tableaupb.Patch.NONE;
}

function isFieldPopulated(msg: AnyMessage, fd: DescField): boolean {
  const v = msg[fd.localName];
  if (v === undefined || v === null) return false;
  switch (fd.fieldKind) {
    case "list":
      return Array.isArray(v) && v.length > 0;
    case "map":
      return typeof v === "object" && Object.keys(v as object).length > 0;
    case "message":
      return true;
    default:
      if (typeof v === "bigint") return v !== 0n;
      if (typeof v === "number") return v !== 0;
      if (typeof v === "string") return v.length > 0;
      if (typeof v === "boolean") return v;
      if (v instanceof Uint8Array) return v.length > 0;
      return true;
  }
}

function clearField(msg: AnyMessage, fd: DescField): void {
  switch (fd.fieldKind) {
    case "list":
      msg[fd.localName] = [];
      break;
    case "map":
      msg[fd.localName] = {};
      break;
    default:
      delete msg[fd.localName];
      break;
  }
}

/**
 * patchMessage patches src into dst, which must be messages with the same descriptor.
 *
 * Default mechanism:
 *   - scalar: populated scalar fields in src are copied to dst.
 *   - message: populated singular messages in src are merged into dst recursively,
 *     or replace dst message if PATCH_REPLACE is specified for the field.
 *   - list: src elements are appended to dst, or replace dst list on PATCH_REPLACE.
 *   - map: src entries are merged into dst, or replace dst map on PATCH_REPLACE.
 */
export function patchMessage(dst: Message, src: Message, desc: DescMessage): void {
  patchMessageInternal(dst as unknown as AnyMessage, src as unknown as AnyMessage, desc);
}

function patchMessageInternal(dst: AnyMessage, src: AnyMessage, desc: DescMessage): void {
  for (const fd of desc.fields) {
    if (!isFieldPopulated(src, fd)) continue;
    if (getFieldPatch(fd) === tableaupb.Patch.REPLACE) {
      clearField(dst, fd);
    }
    switch (fd.fieldKind) {
      case "map":
        patchMap(dst, src, fd);
        break;
      case "list":
        patchList(dst, src, fd);
        break;
      case "message": {
        const name = fd.localName;
        const srcChild = src[name] as AnyMessage;
        const dstChild = dst[name] as AnyMessage | undefined;
        if (dstChild === undefined || dstChild === null) {
          dst[name] = clone(fd.message, srcChild as never);
        } else {
          patchMessageInternal(dstChild, srcChild, fd.message);
        }
        break;
      }
      default:
        dst[fd.localName] = src[fd.localName];
        break;
    }
  }
}

function patchList(dst: AnyMessage, src: AnyMessage, fd: DescField): void {
  const srcList = src[fd.localName] as unknown[];
  let dstList = dst[fd.localName] as unknown[] | undefined;
  if (!Array.isArray(dstList)) {
    dstList = [];
    dst[fd.localName] = dstList;
  }
  const isMessage = fd.fieldKind === "list" && fd.listKind === "message";
  for (const item of srcList) {
    if (isMessage && fd.message) {
      dstList.push(clone(fd.message, item as never));
    } else {
      dstList.push(item);
    }
  }
}

function patchMap(dst: AnyMessage, src: AnyMessage, fd: DescField): void {
  const srcMap = src[fd.localName] as Record<string, unknown>;
  let dstMap = dst[fd.localName] as Record<string, unknown> | undefined;
  if (typeof dstMap !== "object" || dstMap === null) {
    dstMap = {};
    dst[fd.localName] = dstMap;
  }
  const isMessageValue = fd.fieldKind === "map" && fd.mapKind === "message";
  for (const [k, v] of Object.entries(srcMap)) {
    if (isMessageValue && fd.message) {
      const existing = dstMap[k] as AnyMessage | undefined;
      if (existing !== undefined && existing !== null) {
        // NOTE: this MERGES into the existing value (differs from a simple replace).
        patchMessageInternal(existing, v as AnyMessage, fd.message);
      } else {
        dstMap[k] = clone(fd.message, v as never);
      }
    } else {
      dstMap[k] = v;
    }
  }
}

