// Code generated by protoc-gen-go-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-loader v0.8.0
// - protoc                       v3.19.3

package xerrors

import (
	"fmt"
	"github.com/tableauio/loader/test/go-tableau-loader/protoconf/loader/code"
)

type Error struct {
	code  code.Code
	cause error
}

func (e *Error) Code() code.Code {
	if e == nil {
		return code.Success
	}
	return e.code
}

func (e *Error) Error() string {
	if e == nil {
		return "<nil>"
	}
	return fmt.Sprintf("code: %d, cause: %+v", e.code, e.cause)
}

func Errorf(code code.Code, format string, args ...interface{}) error {
	return &Error{
		code:  code,
		cause: fmt.Errorf(format, args...),
	}
}

func Code(err error) code.Code {
	if err == nil {
		return code.Success
	}
	if ferr, ok := err.(*Error); ok {
		return ferr.Code()
	}
	return code.Unknown
}

func Is(err error, code code.Code) bool {
	return Code(err) == code
}
