// Code generated by protoc-gen-go-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-loader v0.10.1
// - protoc                       v3.19.3

package loader

import (
	"errors"
)

var ErrNotFound = errors.New("not found")

func BoolToInt(ok bool) int {
	if ok {
		return 1
	}
	return 0
}
