// Code generated by protoc-gen-go-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-go-tableau-loader v0.11.0
// - protoc                       (unknown)

package loader

import (
	"errors"
)

var ErrNotFound = errors.New("not found")

func boolToInt(ok bool) int {
	if ok {
		return 1
	}
	return 0
}

// GetMessager gets a messager from provided [MessagerMap]. It will return nil
// if not found by messager name.
func GetMessager[T Messager](messagerMap MessagerMap) T {
	var t T
	messager, _ := messagerMap[t.Name()].(T)
	return messager
}
