// Code generated by protoc-gen-cpp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-cpp-tableau-loader v0.10.1
// - protoc                        v3.19.3
// source: hero_conf.proto

#pragma once
#include <filesystem>
#include <string>

#include "load.pc.h"
#include "util.pc.h"
#include "hero_conf.pb.h"

namespace tableau {
class HeroConf : public Messager {
 public:
  static const std::string& Name() { return kProtoName; }
  virtual bool Load(const std::filesystem::path& dir, Format fmt, std::shared_ptr<const load::MessagerOptions> options = nullptr) override;
  const protoconf::HeroConf& Data() const { return data_; }
  const google::protobuf::Message* Message() const override { return &data_; }

 private:
  virtual bool ProcessAfterLoad() override final;

 public:
  const protoconf::HeroConf::Hero* Get(const std::string& name) const;
  const protoconf::HeroConf::Hero::Attr* Get(const std::string& name, const std::string& title) const;

 private:
  static const std::string kProtoName;
  protoconf::HeroConf data_;

  // OrderedMap accessers.
 public:
  using OrderedMap_Hero_AttrMap = std::map<std::string, const protoconf::HeroConf::Hero::Attr*>;
  const OrderedMap_Hero_AttrMap* GetOrderedMap(const std::string& name) const;

  using OrderedMap_HeroValue = std::pair<OrderedMap_Hero_AttrMap, const protoconf::HeroConf::Hero*>;
  using OrderedMap_HeroMap = std::map<std::string, OrderedMap_HeroValue>;
  const OrderedMap_HeroMap* GetOrderedMap() const;

 private:
  OrderedMap_HeroMap ordered_map_;
};

class HeroBaseConf : public Messager {
 public:
  static const std::string& Name() { return kProtoName; }
  virtual bool Load(const std::filesystem::path& dir, Format fmt, std::shared_ptr<const load::MessagerOptions> options = nullptr) override;
  const protoconf::HeroBaseConf& Data() const { return data_; }
  const google::protobuf::Message* Message() const override { return &data_; }

 public:
  const base::Hero* Get(const std::string& name) const;
  const base::Item* Get(const std::string& name, const std::string& id) const;

 private:
  static const std::string kProtoName;
  protoconf::HeroBaseConf data_;
};

}  // namespace tableau

namespace protoconf {
// Here are some type aliases for easy use.
using HeroConfMgr = tableau::HeroConf;
using HeroBaseConfMgr = tableau::HeroBaseConf;
}  // namespace protoconf
