// Code generated by protoc-gen-cpp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-cpp-tableau-loader v0.9.0
// - protoc                        v3.19.3
// source: hero_conf.proto

#include "hero_conf.pc.h"

#include "hub.pc.h"
#include "util.pc.h"

namespace tableau {
const std::string HeroConf::kProtoName = protoconf::HeroConf::GetDescriptor()->name();

bool HeroConf::Load(const std::filesystem::path& dir, Format fmt, std::shared_ptr<const load::MessagerOptions> options /* = nullptr */) {
  tableau::util::TimeProfiler profiler;
  bool loaded = LoadMessagerInDir(data_, dir, fmt, options);
  bool ok = loaded ? ProcessAfterLoad() : false;
  stats_.duration = profiler.Elapse();
  return ok;
}

bool HeroConf::ProcessAfterLoad() {
  // OrderedMap init.
  ordered_map_.clear();
  for (auto&& item1 : data_.hero_map()) {
    ordered_map_[item1.first] = Hero_OrderedMapValue(Hero_Attr_OrderedMap(), &item1.second);
    auto&& ordered_map1 = ordered_map_[item1.first].first;
    for (auto&& item2 : item1.second.attr_map()) {
      ordered_map1[item2.first] = &item2.second;
    }
  }
  return true;
}

const protoconf::HeroConf::Hero* HeroConf::Get(const std::string& name) const {
  auto iter = data_.hero_map().find(name);
  if (iter == data_.hero_map().end()) {
    return nullptr;
  }
  return &iter->second;
}

const protoconf::HeroConf::Hero::Attr* HeroConf::Get(const std::string& name, const std::string& title) const {
  const auto* conf = Get(name);
  if (conf == nullptr) {
    return nullptr;
  }
  auto iter = conf->attr_map().find(title);
  if (iter == conf->attr_map().end()) {
    return nullptr;
  }
  return &iter->second;
}

const HeroConf::Hero_OrderedMap* HeroConf::GetOrderedMap() const {
  return &ordered_map_; 
}

const HeroConf::Hero_Attr_OrderedMap* HeroConf::GetOrderedMap(const std::string& name) const {
  const auto* conf = GetOrderedMap();
  if (conf == nullptr) {
    return nullptr;
  }
  auto iter = conf->find(name);
  if (iter == conf->end()) {
    return nullptr;
  }
  return &iter->second.first;
}

const std::string HeroBaseConf::kProtoName = protoconf::HeroBaseConf::GetDescriptor()->name();

bool HeroBaseConf::Load(const std::filesystem::path& dir, Format fmt, std::shared_ptr<const load::MessagerOptions> options /* = nullptr */) {
  tableau::util::TimeProfiler profiler;
  bool loaded = LoadMessagerInDir(data_, dir, fmt, options);
  bool ok = loaded ? ProcessAfterLoad() : false;
  stats_.duration = profiler.Elapse();
  return ok;
}

const base::Hero* HeroBaseConf::Get(const std::string& name) const {
  auto iter = data_.hero_map().find(name);
  if (iter == data_.hero_map().end()) {
    return nullptr;
  }
  return &iter->second;
}

const base::Item* HeroBaseConf::Get(const std::string& name, const std::string& id) const {
  const auto* conf = Get(name);
  if (conf == nullptr) {
    return nullptr;
  }
  auto iter = conf->item_map().find(id);
  if (iter == conf->item_map().end()) {
    return nullptr;
  }
  return &iter->second;
}

}  // namespace tableau
