// Code generated by protoc-gen-cpp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-cpp-tableau-loader v0.6.0
// - protoc                        v3.19.3
// source: test_conf.proto

#pragma once
#include <string>

#include "hub.pc.h"
#include "test_conf.pb.h"

namespace tableau {
class ActivityConf : public Messager {
 public:
  static const std::string& Name() { return kProtoName; };
  virtual bool Load(const std::string& dir, Format fmt, const LoadOptions* options = nullptr) override;
  const protoconf::ActivityConf& Data() const { return data_; };

 private:
  virtual bool ProcessAfterLoad() override final;

 public:
  const protoconf::ActivityConf::Activity* Get(uint64_t activity_id) const;
  const protoconf::ActivityConf::Activity::Chapter* Get(uint64_t activity_id, uint32_t chapter_id) const;
  const protoconf::Section* Get(uint64_t activity_id, uint32_t chapter_id, uint32_t section_id) const;
  const int32_t* Get(uint64_t activity_id, uint32_t chapter_id, uint32_t section_id, uint32_t key4) const;

 private:
  static const std::string kProtoName;
  protoconf::ActivityConf data_;

  // OrderedMap accessers.
 public:
  using ProtoconfSectionSectionRankMap_OrderedMap = std::map<uint32_t, int32_t>;
  const ProtoconfSectionSectionRankMap_OrderedMap* GetOrderedMap(uint64_t activity_id, uint32_t chapter_id, uint32_t section_id) const;

  using ProtoconfActivityConfActivityChapterSectionMap_OrderedMapValue = std::pair<ProtoconfSectionSectionRankMap_OrderedMap, const protoconf::Section*>;
  using ProtoconfActivityConfActivityChapterSectionMap_OrderedMap = std::map<uint32_t, ProtoconfActivityConfActivityChapterSectionMap_OrderedMapValue>;
  const ProtoconfActivityConfActivityChapterSectionMap_OrderedMap* GetOrderedMap(uint64_t activity_id, uint32_t chapter_id) const;

  using ProtoconfActivityConfActivityChapterMap_OrderedMapValue = std::pair<ProtoconfActivityConfActivityChapterSectionMap_OrderedMap, const protoconf::ActivityConf::Activity::Chapter*>;
  using ProtoconfActivityConfActivityChapterMap_OrderedMap = std::map<uint32_t, ProtoconfActivityConfActivityChapterMap_OrderedMapValue>;
  const ProtoconfActivityConfActivityChapterMap_OrderedMap* GetOrderedMap(uint64_t activity_id) const;

  using ProtoconfActivityConfActivityMap_OrderedMapValue = std::pair<ProtoconfActivityConfActivityChapterMap_OrderedMap, const protoconf::ActivityConf::Activity*>;
  using ProtoconfActivityConfActivityMap_OrderedMap = std::map<uint64_t, ProtoconfActivityConfActivityMap_OrderedMapValue>;
  const ProtoconfActivityConfActivityMap_OrderedMap* GetOrderedMap() const;

 private:
  ProtoconfActivityConfActivityMap_OrderedMap ordered_map_;

  // Index accessers.
  // Index: ChapterID
 public:
  using Index_ChapterVector = std::vector<const protoconf::ActivityConf::Activity::Chapter*>;
  using Index_ChapterMap = std::unordered_map<uint32_t, Index_ChapterVector>;
  const Index_ChapterMap& FindChapter() const;
  const Index_ChapterVector* FindChapter(uint32_t chapter_id) const;
  const protoconf::ActivityConf::Activity::Chapter* FindFirstChapter(uint32_t chapter_id) const;

 private:
  Index_ChapterMap index_chapter_map_;

  // Index: ChapterName@NamedChapter
 public:
  using Index_NamedChapterVector = std::vector<const protoconf::ActivityConf::Activity::Chapter*>;
  using Index_NamedChapterMap = std::unordered_map<std::string, Index_NamedChapterVector>;
  const Index_NamedChapterMap& FindNamedChapter() const;
  const Index_NamedChapterVector* FindNamedChapter(const std::string& chapter_name) const;
  const protoconf::ActivityConf::Activity::Chapter* FindFirstNamedChapter(const std::string& chapter_name) const;

 private:
  Index_NamedChapterMap index_named_chapter_map_;

};

class ChapterConf : public Messager {
 public:
  static const std::string& Name() { return kProtoName; };
  virtual bool Load(const std::string& dir, Format fmt, const LoadOptions* options = nullptr) override;
  const protoconf::ChapterConf& Data() const { return data_; };

 public:
  const protoconf::ChapterConf::Chapter* Get(uint64_t id) const;

 private:
  static const std::string kProtoName;
  protoconf::ChapterConf data_;
};

class ThemeConf : public Messager {
 public:
  static const std::string& Name() { return kProtoName; };
  virtual bool Load(const std::string& dir, Format fmt, const LoadOptions* options = nullptr) override;
  const protoconf::ThemeConf& Data() const { return data_; };

 public:
  const protoconf::ThemeConf::Theme* Get(const std::string& name) const;

 private:
  static const std::string kProtoName;
  protoconf::ThemeConf data_;
};

}  // namespace tableau

namespace protoconf {
// Here are some type aliases for easy use.
using ActivityConfMgr = tableau::ActivityConf;
using ChapterConfMgr = tableau::ChapterConf;
using ThemeConfMgr = tableau::ThemeConf;
}  // namespace protoconf
