// Code generated by protoc-gen-cpp-tableau-loader. DO NOT EDIT.
// versions:
// - protoc-gen-cpp-tableau-loader v0.9.0
// - protoc                        v3.19.3

#pragma once
#include <google/protobuf/message.h>

#include <chrono>
#include <filesystem>
#include <functional>
#include <string>

#include "tableau/protobuf/tableau.pb.h"

namespace tableau {
const std::string& GetErrMsg();
void SetErrMsg(const std::string& msg);

enum class Format {
  kUnknown,
  kJSON,
  kText,
  kBin,
};

extern const std::string kUnknownExt;
extern const std::string kJSONExt;
extern const std::string kTextExt;
extern const std::string kBinExt;

struct MessagerOptions;

namespace util {
// Combine hash values
//
// References:
//  - https://stackoverflow.com/questions/2590677/how-do-i-combine-hash-values-in-c0x
//  - https://stackoverflow.com/questions/17016175/c-unordered-map-using-a-custom-class-type-as-the-key
inline void HashCombine(std::size_t&) {}

template <typename T, typename... O>
inline void HashCombine(std::size_t& seed, const T& v, O... others) {
  std::hash<T> hasher;
  seed ^= hasher(v) + 0x9e3779b9 + (seed << 6) + (seed >> 2);
  HashCombine(seed, others...);
}

template <typename T, typename... O>
inline std::size_t SugaredHashCombine(const T& v, O... others) {
  std::size_t seed = 0;  // start with a hash value 0
  HashCombine(seed, v, others...);
  return seed;
}

// ReadFile reads the file named by filename and returns the contents.
bool ReadFile(const std::filesystem::path& filename, std::string& content);

// GetFormat returns the Format type used by path.
Format GetFormat(const std::filesystem::path& path);
// Empty string will be returned if an unsupported enum value has been passed,
// and the error message can be obtained by GetErrMsg().
const std::string& Format2Ext(Format fmt);

bool JSON2Message(const std::string& json, google::protobuf::Message& msg, bool ignore_unknown_fields);
bool Text2Message(const std::string& text, google::protobuf::Message& msg);
bool Bin2Message(const std::string& bin, google::protobuf::Message& msg);

void ProtobufLogHandler(google::protobuf::LogLevel level, const char* filename, int line, const std::string& msg);

class TimeProfiler {
 protected:
  std::chrono::time_point<std::chrono::steady_clock> last_;

 public:
  TimeProfiler() { Start(); }
  void Start() { last_ = std::chrono::steady_clock::now(); }
  // Calculate duration between the last time point and now,
  // and update last time point to now.
  std::chrono::microseconds Elapse() {
    auto now = std::chrono::steady_clock::now();
    auto duration = now - last_;  // This is of type std::chrono::duration
    last_ = now;
    return std::chrono::duration_cast<std::chrono::microseconds>(duration);
  }
};
}  // namespace util
}  // namespace tableau
