name: Testing Go

# Trigger on pushes, PRs (excluding documentation changes), and nightly.
on:
  push:
    branches: [ master, main ]
  pull_request:
  schedule:
    - cron: 0 0 * * * # daily at 00:00
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            go-version: 1.21.x
          - os: windows-latest
            go-version: 1.21.x

    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install Buf
        uses: bufbuild/buf-action@v1
        with:
          version: 1.67.0
          setup_only: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate protoconf
        working-directory: test/go-tableau-loader
        run: buf generate ..

      - name: Vet
        run: go vet ./...

      - name: Unittest
        run: go test -v -timeout 30m -race ./... -coverprofile=coverage.txt
          -covermode=atomic

      - name: Run loader
        working-directory: test/go-tableau-loader
        run: go run .

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: tableauio/loader
